In [ ]:
%pip install -q pandas pyarrow

import csv
from pathlib import Path

import pandas as pd

DATA = Path("../data")  # repo's data/ folder, one level up from notebooks/

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# ORCAS click logs (~330 MB) and MS MARCO documents (~8.4 GB) go to data/; -C - resumes a partial download.
!curl -L -C - -o "{DATA}/orcas.tsv.gz" https://msmarco.z22.web.core.windows.net/msmarcoranking/orcas.tsv.gz
!curl -L -C - -o "{DATA}/msmarco-docs.tsv.gz" https://msmarco.z22.web.core.windows.net/msmarcoranking/msmarco-docs.tsv.gz

** Resuming transfer from byte position 329653181
  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed

  0      0   0      0   0      0      0      0                              0
100    340 100    340   0      0   1525      0                              0
100    340 100    340   0      0   1524      0                              0
100    340 100    340   0      0   1524      0                              0
** Resuming transfer from byte position 8446274598
  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed

  0      0   0      0   0      0      0      0                              0
100    340 100    340   0      0   1880      0                              0
100    340 100    340   0      0   1880      0                              0
100    340 100    340   0      0   1879      0                              0

In [8]:
# pandas reads .gz directly. QUOTE_NONE and keep_default_na stop stray quotes and queries like "null" from being misread.
orcas = pd.read_csv(
    DATA / "orcas.tsv.gz",
    sep="\t",
    names=["qid", "query", "did", "url"],
    dtype=str,
    quoting=csv.QUOTE_NONE,
    keep_default_na=False,
)
print(orcas.shape)
orcas.head()

(18823602, 4)

,qid,query,did,url
0,9265503,github,D1265400,https://desktop.github.com/
1,9265503,github,D3438005,https://github.com/
2,6832981,youtube,D2923232,https://au.youtube.com/
3,9571352,!,D1238374,https://www.englishclub.com/writing/punctuatio...
4,9571352,!,D889000,http://nationalpunctuationday.com/exclamationp...

In [9]:
# usecols skips the page body, which is most of the file and never used.
docs = pd.read_csv(
    DATA / "msmarco-docs.tsv.gz",
    sep="\t",
    names=["did", "url", "title", "body"],
    usecols=["did", "url", "title"],
    dtype=str,
    quoting=csv.QUOTE_NONE,
    keep_default_na=False,
)
print(docs.shape)
docs.head()

(3213835, 3)

,did,url,title
0,D1555982,https://answers.yahoo.com/question/index?qid=2...,The hot glowing surfaces of stars emit energy ...
1,D301595,http://childparenting.about.com/od/physicalemo...,Developmental Milestones and Your 8-Year-Old C...
2,D1359209,http://visihow.com/Check_for_Lice_Nits,Check for Lice Nits
3,D2147834,http://www.nytimes.com/2010/01/05/business/glo...,Dubai Opens a Tower to Beat All
4,D1568809,http://www.realtor.com/realestateandhomes-sear...,"Coulterville, CA Real Estate & Homes for Sale"